### ISSUE TITLE
Mulighet for å blackliste noen repoer

### ISSUE THREAD

**Issue by heyvard** [navikt/ghep#14]
F.eks. #vault-iac har alle teams som admin, og da får alle disse varslene i sin kanal. 

Tenker man bør blackliste vault-iac, enten globalt, eller legge det inn som option per team

**Comment by heyvard** [comment]
Eksempel på vault meldinger ser man i https://nav-it.slack.com/archives/C04GJK1L4S2/p1706781854830079

**Comment by Kyrremann** [comment]
Tenker jeg lager en global blocklist og slenger inn den og `aad-iac`.
